# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\temp_humi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("background-color: rgb(255, 250, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 760, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.label_name_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_name_temp.setGeometry(QtCore.QRect(20, 430, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_temp.setFont(font)
        self.label_name_temp.setObjectName("label_name_temp")
        self.label_value_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_value_temp.setGeometry(QtCore.QRect(110, 430, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_value_temp.setFont(font)
        self.label_value_temp.setText("")
        self.label_value_temp.setObjectName("label_value_temp")
        self.label_value_humi = QtWidgets.QLabel(self.centralwidget)
        self.label_value_humi.setGeometry(QtCore.QRect(420, 430, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_value_humi.setFont(font)
        self.label_value_humi.setText("")
        self.label_value_humi.setObjectName("label_value_humi")
        self.label_name_humi = QtWidgets.QLabel(self.centralwidget)
        self.label_name_humi.setGeometry(QtCore.QRect(330, 430, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_humi.setFont(font)
        self.label_name_humi.setObjectName("label_name_humi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name_temp.setText(_translate("MainWindow", "Temp"))
        self.label_name_humi.setText(_translate("MainWindow", "Humi"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
